const QUESTION_TYPES = {
  OPEN_ANSWER: "1",
  TEST_UNIQUE_ANSWER: "2",
  TEST_MULTIPLE_ANSWER: "3"
};

const TYPE_QUESTION_ANSWERS = {
  INCORRECT: false,
  CORRECT: true
};

const FIREBASE_TOKEN = "";

const TYPEFORM_TOKEN = "";

export default { QUESTION_TYPES, TYPE_QUESTION_ANSWERS, FIREBASE_TOKEN, TYPEFORM_TOKEN};
